name: Workflow Test Actions workflow

on: [push]

jobs:
  job-run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Step simple JavaScript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Monster Reddy"
      - name: Step Log Greeting time
        run: echo "Hello" + "${{ steps.greet.outputs.time }}"