name: Workflow Test Actions workflow

on: [push]

jobs:
  job-run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Step List down the Files and Path before anything else
        run: |
          pwd
          ls -ltra
          echo ${{ GITHUB_SHA }}
          echo ${{ GITHUB_REPOSITORY }}
          echo ${{ GITHUB_WORKSPACE }}
          echo ${{ github.token }}
      - name: Step simple JavaScript Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: "Monster Reddy"
      - name: Step List down the Files and the Path After the  Javascript Actions were executed
        run: |
          pwd
          ls -ltra
      - name: Step Checkout my Repo files to remote virtual machine
        uses: actions/checkout@v1
      - name: Step List down the Files and the Path After the checkout the files to the remote Repo
        run: |
          pwd
          ls -ltra
      - name: Step Log Greeting time
        run: echo "Hello" + "${{ steps.greet.outputs.time }}"