name: Workflow Test Gangi Shell Commands

on: [push]

jobs:
  job-run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Step echo a string
        run: echo "Hello World"
      - name: Step multiline script
        run:  |
          node -v
          npm -v